Add log2 of coverage for final output
sanger-tol/treeval pull request #160
Opened 2023-10-11 14:47 UTC by weaglesBio

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [-] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/treeval/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [-] Usage Documentation in `docs/usage.md` is updated.
- [-] Output Documentation in `docs/output.md` is updated.
- [-] `CHANGELOG.md` is updated.
- [-] `README.md` is updated (including new tool citations and authors/contributors).

Updated the longread coverage subworkflow to log2 the coverage value produced by genomecoverage. This is sorted then converted to bigwig.

2023-10-11 14:58 UTC, DLBPointon requested changes

2023-10-11 14:58 UTC, DLBPointon commented on hs_err_pid21943.log
Can you delete this log file. Other than that, looks good.

2023-10-11 15:00 UTC, yumisims commented on hs_err_pid21943.log
I didn't even test locally just added data set, and using github UI to do the change, I will get that done now.

2023-10-25 09:18 UTC, DLBPointon approved these changes

2023-10-25 12:42 UTC, merged