Dp24 pretextgraph
sanger-tol/treeval pull request #164
Opened 2023-10-26 14:42 UTC by DLBPointon

Pretext Ingestion!

The accessory files are now ingested into the pretext file, rather than needing the end user to ingest them independently.
coverage, log2 coverage and repeat density are ingested by default and telomere + gap are ingested if they contain > 0 bytes. 

This highlighted a small bug with the new log_coverage track, which has been corrected with a `round(value, 2)` ensuring that there will always be a whole number for ingestion and no data is skipped.

2023-10-26 15:31 UTC, DLBPointon commented
Pipeline fails as it needs Pretext_hires to be emitted from hic_mapping but can't as pretext_hires needs 16GB minimum

2023-11-02 16:35 UTC, DLBPointon commented
This PR has grown a bit, so to summarise:
- Multiple fixes to longreadlogcoverage
- Adding logcoverage to pretextgraph
- Adding pretextgraph
- Updating and fixing docs (will become clear once added to dev)
- Stopped exporting pre.bed
- Start exporting another repeat coverage file for use in JBrowse2

2023-11-06 10:45 UTC, weaglesBio requested changes

2023-11-06 10:45 UTC, weaglesBio commented on docs/images/v1-1-0/treeval_1_1_0_generate_genome.png
1. Terminator is not used in other images, is it needed or clear what it is doing.
2. Fasta label is capitalised, other examples are not.

2023-11-06 10:45 UTC, weaglesBio commented on nextflow.config
Does cleanup = true need to be added locally, or will it be globally added to the sanger profile?

2023-11-06 10:53 UTC, DLBPointon commented on docs/images/v1-1-0/treeval_1_1_0_generate_genome.png
Fixed

2023-11-06 10:56 UTC, DLBPointon commented on nextflow.config
I've reverted this so, cleanup is not back as a profile. I just forgot what I wrote does.
To use, do `-profile singularity,sanger,cleanup`

This way it is optional and global.

2023-11-07 09:53 UTC, weaglesBio approved these changes
Same Fasta issue on gap_finder, insilico_digest (with Genome also) and the full diagram. This is not a blocker though.

2023-11-07 09:55 UTC, merged