Readcov
sanger-tol/treeval pull request #193
Opened 2024-01-10 13:56 UTC by DLBPointon

2024-01-10 14:09 UTC, weaglesBio requested changes

2024-01-10 14:09 UTC, weaglesBio commented on assets/local_testing/nxOscDF5033.yaml
Will need to apply this update to all test .yaml

2024-01-10 14:09 UTC, weaglesBio commented on conf/modules.config
Will MINIMAP2_ALIGN_ILLUMINA need to be included in this?

2024-01-10 14:09 UTC, weaglesBio commented on subworkflows/local/yaml_input.nf
Is this necessary if same name? (read_ch)

2024-01-10 14:09 UTC, weaglesBio commented on conf/modules.config
Also MINIMAP2_ALIGN_SE

2024-01-10 14:11 UTC, DLBPointon commented
linting failing you need to run `nf-core modules patch` to fix

2024-01-10 14:13 UTC, yumisims commented
Ok I will run and resubmit
thanks

From: Damon-Lee Pointon ***@***.***>
Reply to: sanger-tol/treeval ***@***.***>
Date: Wednesday, 10 January 2024 at 14:12
To: sanger-tol/treeval ***@***.***>
Cc: Ying Sims ***@***.***>, Assign ***@***.***>
Subject: Re: [sanger-tol/treeval] Readcov (PR #193) [EXT]


linting failing you need to run nf-core modules patch to fix

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sanger-2Dtol_treeval_pull_193-23issuecomment-2D1884925168&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=X9VPYUGy4ibZarh9Rup1XaZ62i2u-I0xOZXEy11dXDM&m=Zf3BV4rrlwX-8B-At8EgG2q2joumnQmeRgBi0TUyRg8zYi9zyczGHsZUSpxSW0jk&s=dfpIplo6BuMexXCzD9FlVM72RRi4F0QPsc5WL4CEnT4&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADHNWY5E3MSF4HITI4RJSVTYN2OSXAVCNFSM6AAAAABBU2XD6CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBUHEZDKMJWHA&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=X9VPYUGy4ibZarh9Rup1XaZ62i2u-I0xOZXEy11dXDM&m=Zf3BV4rrlwX-8B-At8EgG2q2joumnQmeRgBi0TUyRg8zYi9zyczGHsZUSpxSW0jk&s=KSrJCiSzG71nHYBtmplLO-gAeFmxfAMl1IO_mkpSOyA&e=>.
You are receiving this because you were assigned.Message ID: ***@***.***>



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is Wellcome Sanger Institute, Wellcome Genome Campus, 
 Hinxton, CB10 1SA

2024-01-11 15:58 UTC, yumisims commented on subworkflows/local/yaml_input.nf
better to be

2024-01-11 15:59 UTC, yumisims commented on conf/modules.config
se and pe are not needed in the workflow any longer

2024-01-11 15:59 UTC, yumisims commented on conf/modules.config
> +    withName: MINIMAP2_ALIGN {
it has been changed

2024-01-12 10:03 UTC, merged