Dp24 moving logic
sanger-tol/treeval pull request #248
Opened 2024-02-09 11:59 UTC by DLBPointon

Removing logic from. thesubworkflow and into the modules.config.
Re-enable snapshot-hires.
CI update

Closes #226

2024-02-12 14:57 UTC, weaglesBio requested changes

2024-02-12 14:57 UTC, weaglesBio commented on conf/modules.config
It should be args2 for gap finder as well, as it is a tabix argument.

2024-02-12 15:29 UTC, DLBPointon commented on conf/modules.config
Nice catch. Corrected now. Odd that it didn't confuse bgzip.

2024-02-13 16:30 UTC, weaglesBio approved these changes

2024-02-13 16:31 UTC, merged